"""add_users_and_api_keys_relationships

Revision ID: 0d2ee2341b80
Revises: 66f8bf091d62
Create Date: 2026-06-23 20:11:35.422177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2ee2341b80'
down_revision: Union[str, None] = '66f8bf091d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'user'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('api_keys', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('assessments', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('assessments', sa.Column('api_key_id', sa.UUID(), nullable=True))
    op.add_column('assessments', sa.Column('error_traceback', sa.String(), nullable=True))
    op.create_foreign_key(None, 'assessments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assessments', 'api_keys', ['api_key_id'], ['key_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'error_traceback')
    op.drop_column('assessments', 'api_key_id')
    op.drop_column('assessments', 'user_id')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_column('api_keys', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
